server:
  port: 8080

spring:
  application:
    name: user-center
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/laydb?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

